import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/landing/debug1">Debug page for SDK V1</Link>
        <br/>
        <Link href="/landing/debug2">Debug page for SDK V2</Link>
      </main>
    </>
  )
}
